RedHatInsights/xjoin-operator

README.md, dev/setup-clowder.sh
This PR adds MacOS related to steps to deploy `xjoin-search` to minikube using `xjoin-operator`.
=> update README for MacOS related steps

README.md, config/samples/xjoin_v1alpha1_xjoinindex.yaml, controllers/config/parameters.go, controllers/data/types.go, deploy/clowder.yaml, deploy/operator.yml
Replaces #6. Accompanies [xjoin-search PR 125](https://github.com/RedHatInsights/xjoin-search/pull/125).
Also adds "inventory-db" back into /etc/hosts in the README, since it turns out that's also still needed during the setup process.
=> Case-insensitive tag filtering

dev/cleanup.projects.sh, dev/setup.sh
Support podman's secrets file to create pull secrets on local cluster from.
Use `patch` instead of `apply` on xjoinpipelines when deleting namespace in projects cleanup.
=> chore(dev): poman secrets and cleanup fixes

controllers/pipeline/iteration.go, controllers/pipeline/validate.go
standard math functions should be preferred
ESSNTL-4192
=> refactor: use math.Abs instead

controllers/database/database.go
Maps are unordered, hence the sort function from utilities is ineffective.
TODO:
ESSNTL-4192
=> refactor: drop use of SortMap

controllers/database/database.go, controllers/elasticsearch/data.go
Standardize timeformat on [`time.RFC3339Nano`](https://pkg.go.dev/time@go1.18#pkg-constants).
Previous format was [`2006-01-02T15:04:05.999999999`](https://github.com/RedHatInsights/xjoin-go-lib/blob/24227803ebad47655e6a3b3eb6ab3987bed0478c/pkg/utils/lang.go#L100).
References: 
* https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html
* https://www.postgresql.org/docs/13/datatype-datetime.html
ESSNTL-4192
=> refactor: use time.RFC3339Nano format

controllers/common/reconciler.go, controllers/components/custodian.go, controllers/datasource/datasource_reconciler.go, controllers/index/index_reconciler.go, controllers/index/xjoinindexvalidator_iteration.go, controllers/parameters/index_parameters.go, controllers/xjoinindexvalidator_controller.go, controllers/xjoinindexvalidator_controller_test.go
Without this fix, when a component deletion fails, e.g. when apicurio is unavailable, then the entire scrub method aborts. This lead to some components never being deleted.
=> [ESSNTL-4204] Continue scrubbing after single component deletion fails

.gitleaks.toml, config/crd/bases/monitoring.coreos.com_prometheuses.yaml
This PR removes the leftover sample and allowlist, which should have been removed by dummy and whitelist by the revert of PR but did not.  With this merge, the rude words will be fully back in and the number of changed files in PR #39 will go down to 3.
=> Put back the leftover dummy and whitelist

controllers/components/custodian.go, controllers/config/parameters.go, controllers/suite_test.go
This PR updates comments which are not compliant and keep getting updated when dlv is running for debugging test, thereby messing up the number of truely changed files.
=> Updated comments reformatted by running dlv execution

Makefile, README.md
This PR updates link to the `XJoin pipeline` doc page.  It also changes the `delve-test` target in makefile to run the tests in the `contollers` folder and not just the ones in `controllers/test`
=> Fix a link url and test to folder to run in

dev/get_credentials.sh
This PR adds project name to the get secrets command, otherwise the get_credentials script fails when the default project name is not set.
=> Add project name to get secrets command

Dockerfile
Bumping up the the build image version to 1.18.10
=> bumping the builder go-toolset to match microdnf

Dockerfile
Bumping the go toolset to 1.19.6 as it the only version UBI8 minimal has access to now
=> bumping go toolset yet again

Dockerfile
Changed the go call outs to be x and y and not x, y, and z  (example 1.19 instead of 1.19.6)
=> Bumping the go-toolset

.github/workflows/update_mapping.yaml
This patch is an attempt to fix the uncontrollable Update Mapping workflow, which was creating multiple and identical PRs instead of one.
=> Fix Update Mapping workflow

Dockerfile
Updating the CGO_Enabled flag to 1 to see if it breaks as it is needed for FIPS
=> Updating CGO Flag

.github/workflows/checkimage.yaml, .github/workflows/update_mapping.yaml
Updates the `update_mapping` and `checkimage` workflows so that they don't step on each others' toes. Right now they attempt to push to the same branch, and since the latest base-image PR wasn't merged, the `update_mapping` workflow sees that PR and decides there's nothing to do.
I also told it to delete its working branch once the PR is merged or closed.
=> Specify branch in git actions

scripts/package-lock.json, scripts/package.json, scripts/update_mapping.js
Swaps out the `json-schema-to-es-mapping` dependency for the one used by xjoin-search
=> Swap out es-mapping for the one used by xjoin-search

controllers/kafka/strimzi-connectors.go
Catch the error that is causing the pods to fall over
=> Fix bug in kafka connect reconciler

Dockerfile
Fix the build so that it runs.
The go-toolset-1.19.9 package didn't exist. Updated to the procedure I found in the [Docs](https://access.redhat.com/documentation/en-us/red_hat_developer_tools/1/html/using_go_1.19.6_toolset/assembly_go-toolset#proc_installing-comp-toolset_assembly_go-toolset)
=> fix: dockerfile fixes for golang install

build_security_catalog.sh
This PR updates the Security-Compliance Tag Naming Convention within the `build_security_catalog.sh` to make it easier to identify the Git Commit the image is based on.
Example:
OLD: `security-compliance`
NEW: `sc-20230920-f963f6f`
=> Update Security Catalog Script with New Tagging Convention

Dockerfile
Remove go toolset from the running image. This should be used for dev only and not have an impact on running the actual app.
=> task: Remove go-toolset from running image

build_deploy.sh
The multiarch build doesn't leave the original image in place so we have to build it when we use sec comp
=> Fix issues with building image

Dockerfile
Reverts RedHatInsights/xjoin-operator#181
It looks suspiciously like this broke the PR checks, so I want to try reverting this. If it remains broken, I'll revert this.
=> Revert "fix: Remove go toolset from running image"
